name: anyq
version: 1.0.0
channels:
  cli:
    uses: channels.wasmflow.cli@v1
    with:
      location: ./cli-anyq/anyq-cli/build/anyq_cli.signed.wasm
      component: anyq-cli
      link:
        kind: Manifest
        reference: ./cli-anyq/anyq-cli/anyq.wafl